### ISSUE TITLE
Pagination is not reset when returning to Home

### ISSUE THREAD

**Issue by Nh640** [flightlesstux/S3-Directory-Listing#12]
Hello,

thanks for the pagination improvement, it works great. Nevertheless, if I am browsing a bucket with a great amount of pages and I want to return Home, the pagination preserves the last page number and I need to totally refresh the website or move to the first page one by one. I think it could be great to reset the page index when clicking on the Home link.

Regards.

**Comment by flightlesstux** [comment]
I'll continue on https://github.com/flightlesstux/S3-Directory-Listing/issues/13.
