### ISSUE TITLE
No more than a thousand items are retrieved

### ISSUE THREAD

**Issue by Nh640** [flightlesstux/S3-Directory-Listing#13]
Hello,

sorry but I mixed two topics in my initial issue: pagination and the retrieval of more than a thousand items. By default S3 API will return a thousand items at a maximum, so the rest can't be shown with the listing tool. Is it possible to continue fetching the rest of the objects using the continuationToken provided by S3 and have them visible in the list?

Regards.

**Comment by flightlesstux** [comment]
HI @Nh640 I'll check it. Thank you for the suggestion!

**Comment by flightlesstux** [comment]
Hello @Nh640,

I've implement the `continuationToken` feature and pushed to main branch. You can also see a demo. I hope, it'll work for you and will helps you.

Best,
Ercan

**Comment by danbeibei** [comment]
Hi there,

It doesn't work on my side. I'm stuck with a max of 1000 listed objects.
The "Next" button is grayed out. The max page number displayed at the bottom ("Page X of Y") corresponds to the number of pages for 1000 objects.
I printed the value of `keys.length` in the `listObjects` function, and it is 1000 while there is 1122 objects in my bucket.
I'm definitely not competent to understand what is happening, hoping you can take a look.

Regards,
Daniel
