### ISSUE TITLE
No pagination for buckets with more than 1000 items

### ISSUE THREAD

**Issue by Nh640** [flightlesstux/S3-Directory-Listing#3]
Hello,

I really like this tool, but It is not working as expected when I want to navigate a folder containing more than a thousand items. When this number is exceeded we should have the option to use pagination and continue looking the rest of the items.

Regards.

**Comment by flightlesstux** [comment]
Hello @Nh640,

Thank you for your feedback. Now, I've added pagination support, and you can use!
